ossf/scorecard-action

- policies/template.yml
- run-analysis/Dockerfile
- run-analysis/action.yaml
- run-analysis/entrypoint.sh
Files to run the scorecard action.
See this file to see how to use it from a workflow https://github.com/laurentsimon/scorecard-action-test-4/blob/main/.github/workflows/scorecard-analysis.yml#L24
The branch is set to this PR branch for testing only - by default main branch is used and it not necessary.
> ✨ run-analysis action files

- analyze/action.yaml
> Make policy file a non-required argument

- action.yaml
Use new image container
Note: this needs to be pinned before actual release
> Update action.yaml to use new image

- Dockerfile
- entrypoint.sh
closes https://github.com/ossf/scorecard-action/issues/19
See title for description.
> feature: add support for branch protection trigger

- .github/workflows/docker-sign.yml
Fixes https://github.com/ossf/scorecard-action/issues/12
> Fixed the location of the dockerfile

- action.yaml
An idea to give an incentive for users to upload their results. Thoughts?
> Change name of arguments to share crowdsource results

- action.yaml
> Set default for non-required actin arguments

- entrypoint.sh
We've renamed the env variable from `SCORECARD_V4` to `ENABLED_SARIF` in https://github.com/ossf/scorecard/pull/1405. This PR updates the variable when running the action.
> Update variable name to enable SARIF

- README.md
Adds documentation for the action.
fyi, you can visualize the readme at https://github.com/laurentsimon/scorecard-action/tree/feat/doc#readme
closes https://github.com/ossf/scorecard-action/issues/18
> ✨ Add documentation

- policies/template.yml
See title.
closes https://github.com/ossf/scorecard-action/issues/28
> ✨ Remove signed-release check from action

- Dockerfile
> ✨ Bump hash

- README.md
We need to update the permissions for this to work on private repos, it seems.
> Update job permissions

- Dockerfile
Update the hash to the latest stable version of scorecard, which is used for the V4 release.
> V4 release hash update

- README.md
Update the hash in the example workflow
> Update the hash in the doc

- README.md
Add Troubleshooting under Verifying Runs for "run failed" messaging;
Add "Upload artifact" explanation (heading section and in Workflow Example comments)
Add link for workflow file setup documentation 
Add Table of Contents with links to headings
Fix typos, formatting
> Olivekl update install 2

- README.md
> Update README.md with v1.0.1 hash

- README.md
I did not follow my own process and update the hash before the release, instead of the other way around.
> Bump the hash in doc

- entrypoint.sh
Let's use `$GITHUB_REPOSITORY` instead of querying the context's json file.
> use GITHUB_REPOSITORY in shell script

- action.yaml
> 🐛  Fix default parameter requirement

- README.md
> Bump hash in README for v1.0.4

- Dockerfile
See https://github.com/ossf/scorecard-action/pull/118#pullrequestreview-893067144
> Include version in docker dependency

- policies/template.yml
The remediation section states that only a passing score is required for this check to pass:
> We give full credit to projects that meet the passing criteria, which is a significant achievement for many projects.
A passing score currently equals 5.
https://github.com/ossf/scorecard/blob/e128c3de82607e1b285185da9c76a5262255b180/checks/cii_best_practices.go
See #110 for more details.
> Align the CII-Best-Practices requirements with the documentation

- Dockerfile
The new Dockerfile will remain on the `golang-staging` branch to be further tested.
> Revert Dockerfile to Shell Script

- README.md
Update doc with PAT for private repos
```release-notes
Update doc with PAT for private repos
```
> Update doc with PAT for private repos

- Dockerfile
Update hash to latest scorecard to scorecard HEAD to test.
Once this is merged, I'll manually run the e2e tests
> Update hash to latest scorecard

- e2e/README.md
I have updated the e2e tests to include more corner cases using GitHub Actions `matrix`. Updating the e2e repo and filename information here to reflect the latest changes.
> 📖 Update e2e repo info

- multi-repo-action/README.md
Based on the discussion from this https://github.com/ossf/scorecard-action/pull/773
> multi-repo-action: Note that tool is a work-in-progress

- LICENSE
- Fixes https://github.com/ossf/scorecard-action/issues/851
> :seedling: Included License

- action.yaml
> :seedling: Release v2.0.0

- action.yaml
- options/options.go
- options/options_test.go
- Fixes the failing tests in https://github.com/ossf/scorecard-action/pull/896
> 🐛 Fixes Run all checks on a BranchProtection event - failing tests 

- action.yaml
Release a new patch with #898 fix
> ✨ Create v2.0.3 patch

- Dockerfile
- action.yaml
Fix - https://github.com/ossf/scorecard-action/issues/978
> Fix - Broken dockerfile

- .github/workflows/docker-image.yml
> Docker build workflow

- .golangci.yml
- Fixed the dead linter warnings
> Fix - golangcilint warning

- action.yaml
Signed-off-by: laurentsimon <64505099+laurentsimon@users.noreply.github.com>
> Minor release v2.1.0

- README.md
fixes https://github.com/ossf/scorecard-action/issues/1398
> docs: dogfooding badge

- action.yaml
Please do not merge yet, waiting for another run or two of the e2e tests:
https://github.com/ossf-tests/scorecard-action/actions/workflows/scorecards-head.yml
> :seedling: bump docker to ghcr v2.4.3
