policies/template.yml

adjust the score for the Maintained check to pass to 1 instead of 10. Score of 10 means there are a large number of commits/activity in the past 90 days. We don't want to show this in the scanning results so long as there is *some* activity.

🐛 Adjust maintained score

---

README.md

Rename token in workflow to `SCORECARD_READ_TOKEN`, as in the updated documentation in https://github.com/ossf/scorecard-action/pull/46

Rename token name

---

README.md

New Starter Workflow refers to SCORECARD_READ_TOKEN but README uses SCORECARD_TOKEN. Making the variable name consistent.

Fixing repo token secret typo

---

Dockerfile

See https://github.com/ossf/scorecard/issues/1479 for details

Bump dockerfile hash to fix SARIF semVer

---

README.md

This https://github.com/ossf/scorecard/issues/1504 for details.
cc @nibanks thanks for the original report!
closes https://github.com/ossf/scorecard/issues/1504

📖 Add doc about SAML SSO

---

entrypoint.sh

see https://github.com/ossf/scorecard-action/issues/66
@mariuszkrzaczkowski  can you verify this fixes your problem by using `uses: laurentsimon/scorecard-action@feat/defbranch` in your workflow? Once you confirm, I'll push and release the fix. Thanks!
closes https://github.com/ossf/scorecard-action/issues/66

🐛 Support arbitrary default branch

---

Dockerfile
entrypoint.sh

The `repository.private` and `repository.default_branch` are null when the action is triggered by a `schedule` trigger.
I think this is a bug and I've created a support issue on GitHub to ask.
There is another field `master_branch` but it may be deprecated in the future so I would like to avoid it.
To fix the issue, I'm querying a REST API instead, which seems more reliable.
closes https://github.com/ossf/scorecard-action/issues/73

🐛 Fix null default branch/private fields

---

entrypoint.sh

entrypoint.sh: add warning if token is empty
Add warning to let users know how to fix an empty PAT token.
Add additional warning if the repo is a fork.
closes https://github.com/ossf/scorecard-action/issues/70

✨ Add warning for empty repo token

---

.github/workflows/codeql-analysis.yml
.github/workflows/golangci.yml
.golangci.yml

- Included golangci for clean code.
- Included `go` for codeql
- created a new separate action for the golangci - to keep the action file simple and also it enables them to run cocurrently.
-  Include actions cache for caching workflow runs.

:seedling: Golang CI for clean code.

---

main.go
main_test.go

- Porting the shell script to go
- Including additional tests
- Code cleanup for the linter.

:seedling: Porting shell script to Go

---

.github/workflows/tests.yaml
main.go
main_test.go

🌱 More tests

---

entrypoint.sh

Given that `GITHUB_EVENT_PATH` is not set for a `schedule` event, we need to get the info about whether a repo is a fork or not from a different source.
closes https://github.com/ossf/scorecard-action/issues/84

🐛 Fix null is fork in script

---

main.go
main_test.go

More porting of shell script to go.
Tests associated with the new changes.

:seedling: Porting of shell script to go

---

go.mod
go.sum
main.go
main_test.go

- Final bits of porting the shell script to `go`
- Tests included for the commandline args to Scorecard.

:seedling: Final bits of porting the shell to go

---

.github/workflows/tests.yaml
go.mod
go.sum

- Verify go mod tidy and go mod verify
- Verify git porcelain

:seedling: Verify clean env in build

---

.github/workflows/tests.yaml
main.go
main_test.go

issue #107 
Moving the following variables in main.go from env vars to native Go vars.

Remove env vars

---

.github/workflows/golangci.yml
.golangci.yml

Fixes needed for https://github.com/ossf/scorecard-action/pull/122.
From https://golangci-lint.run/usage/linters/#gci:
```yaml
linters-settings:
gci:
local-prefixes: github.com/org/project
no-inline-comments: true
no-prefix-comments: true
sections:
- standard # Captures all standard packages if they do not match another section.
- default # Contains all imports that could not be matched to another section type.
- comment(your text here) # Prints the specified indented comment.
- newLine # Prints an empty line
- prefix(github.com/org/project) # Groups all imports with the specified Prefix.
section-separators:
- newLine
```
`local-prefixes` is deprecated, so we use `sections` here instead.
Because of a few things:
- dependabot automatically updates golangci-lint-action versions
- the `gci` …

golangci-lint: Fix GCI warnings

---

README.md

To simplify the selection of the scopes by users setting this up, we can
use the `scopes` querystring parameter to add the scopes we need.

Pre-fill `scopes` on creation of the PAT

---

Dockerfile
options/options.go

Changed the Dockerfile to use entrypoint.go instead of the shell script.
todo: add e2e tests

Dockerfile Build Using Golang Entrypoint

---

action.yaml
options/options_test.go

Set default token to be GITHUB_TOKEN.
Users don't need to provide it, unless they want to get the Branch-Protection results.
I'll update the README in a separate PR.

✨ Set default token as GITHUB_TOKEN

---

README.md
options/options_test.go

See title
closes https://github.com/ossf/scorecard-action/issues/80
closes https://github.com/ossf/scorecard-action/issues/78

✨ Update documentation

---

README.md

Amend documentation for private repos
```release-notes
Amend documentation for private repos
```

✨ Amend documentation for private repos

---

README.md

See https://github.com/ossf/scorecard-action/issues/292
closes https://github.com/ossf/scorecard-action/issues/292

📖 Fix documentation link

---

Dockerfile

Update container hash for v1.1.0 s that we can release v1.1.0 https://github.com/ossf/scorecard-action/issues/97
```release-notes
Update container hash for v1.1.0
```

✨ Update container hash for v1.1.0

---

.github/workflows/dependency-review.yml

- Dependency review check included.
Source repository: https://github.com/actions/dependency-review-action
Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement

:seedling: .github: Add dependency review action

---

README.md

Update hash of example to v1.1.0's hash

✨ Update hash of example

---

README.md

📖  Update example hash for v1.1.1

---

entrypoint.sh

Referring to an unset var causes `unbound variable` error. Check if the var is set before we refer to it. Fixes #386.

🐛 Avoid error on `json` and `default` inputs

---

.dockerignore
.gitignore
Dockerfile
docs/development.md

(Pulled these file changes from https://github.com/ossf/scorecard-action/pull/316, since that PR is still pending)
- Incorporates container image build/test docs into repo documentation
- Update references in `Dockerfile` to point to the build/test docs
- Adds a .dockerignore file (which is a symlink to .gitignore)
Signed-off-by: Stephen Augustus <foo@auggie.dev>

📖 docs: Add instructions on building/testing container image

---

Makefile
options/options.go

Fixes 2 diffs that currently show up in Golang action results vs. the current bash one:
- Inject Scorecard version and commitSHA into Golang action through ldflags
- Set `showDetails` to `true` in Golang action.

🌱 Fix some diffs between Golang and current action

---

.github/workflows/tests.yaml
signing/signing_test.go

CI-Tests are failing because of authentication issues. This PR should hopefully fix that.

🐛 Fix intermittent failures in CI-Tests

---

README.md

scorecard-action:v2 only works with certain approved GH actions. Clearly document this restriction for users.

📖 Update README about the restrictions for scorecard-action:v2

---

signing/signing.go

Explicitly adds `application/json` request header. API calls with stricter verification fail without this header.

🐛 Add request application/json request header

---

action.yaml
signing/signing.go

The fixes made in #791 need to be released to users. So creating a alpha release.
This PR also allows for the API url to be overridden. Used in e2e tests.
Part of #801.

Create a new release v2.0.0-alpha.1

---

README.md

Edits for clarity (and typo) to v2 breaking changes section.

Olivekl patch 1

---

install/install.go

The file is wrongly created at `/scorecards.yml` instead of `.github/workflows/scorecards.yml`.

Fix workflow path in automatic creation of PR 

---

README.md

PR adds docs to show REST API usage.

📖 Add docs for API

---

Makefile
entrypoint/entrypoint.go
go.mod
go.sum

This is a proper fix for #856.
As of [scorecard v4.7.0](https://github.com/ossf/scorecard/releases/tag/v4.7.0), runtime errors encountered during checks now produce a `ErrorCheckRuntime` error. These errors could be expected, for example repos with branch protection enabled but did not provide a PAT (currently a known limitation of scorecard). Or they could be from unexpected conditions / secondary rate limits.
These errors started bubbling up in scorecard v4.6.0, and while this was beneficial for CLI users of scorecard it broke the existing behavior of scorecard-action. To restore the behavior, scorecard-action now checks for these specific scorecard errors and continues to silently ignore them. 
e2e tests which would have caught #856 have been added in …

🐛 Restore behavior of ignoring scorecard runtime errors

---

action.yaml

Signed-off-by: Spencer Schrock <sschrock@google.com>
Proper fix for #856 that reverts scorecard downgrade. Now uses scorecard v4.7.0

Create v2.0.4 patch

---

.github/workflows/tests.yaml
Dockerfile
go.mod

:seedling: Upgrade to go 1.19

---

Dockerfile

- Distroless containers
This should wait until we have #981 merged 

:seedling: Distroless container

---

starter-workflows/code-scanning/scorecards.yml

Closes #977 
Regarding the issue #977, I couldn't think of a better way of doing this instead of adding the if clause to the default yml file, let me know if I missed some better idea to fix.

🐛 Fix to not upload the result in the security dashboard if it is a pull request

---

Dockerfile

root is needed to support GHA
https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user
The policy file is also needed or the [action will fail](https://github.com/spencerschrock/scorecard-action-branch-protection-e2e/actions/runs/3322399756/jobs/5491366014#step:4:200). In the future we should double check this is the policy we expect to be used.
```
2022/10/25 15:52:42 error during command execution: readPolicy: internal error: os.ReadFile: open /policy.yml: no such file or directory
```
This Dockerfile was tested locally and with GHA
https://github.com/spencerschrock/scorecard-action-branch-protection-e2e/actions/runs/3322399756
Fixes #989 
Fixes #990 
Fixes #991 
Fixes #992 
Fixes #993

🌱 Use root user in distroless to support GitHub Actions

---

README.md

-Add a dedicated section to explain risks of using a PAT
-Reorder installation instructions and remove content that repeats the new section

Add PAT section explaining risks

---

README.md

I have copied that line a couple of times and forgot to remove the spaces in it more than once 🙈 . 
Making it a one line will prevent more users from going through this cycle (there where two spaces, so often two extra commits before it worked!).
Also updated the `org` variable --> `owner`, since you can either have an organization repo or a user repo, so it's common to refer to `owner`.

Make the badge text easier to copy

---

README.md

Make the documentation explicit by mentioning that this action also needs to be called from the original location, otherwise it will fail with a non-descriptive error, as discussed in #1028.
closes https://github.com/ossf/scorecard-action/issues/1028
Signed-off-by: Rob Bos <rajbos@users.noreply.github.com>

Complete the list of required actions

---

Makefile
go.mod
go.sum

Signed-off-by: Spencer Schrock <sschrock@google.com>
Bug report at https://github.com/ossf/scorecard/pull/2557 for details.

🌱 Bump scorecard dependency to v4.10.2 to remove a CODEOWNERS printf statement.

---

action.yaml

Signed-off-by: Spencer Schrock <sschrock@google.com>
I've manually tested the action, as the steps in [RELEASE.md](https://github.com/ossf/scorecard-action/blob/7da02bf0d58396bc404a7e5aef3e9b0c24dcb9bc/RELEASE.md#validate-the-action) don't actually test any new changes since the docker image is pinned to a version.
I've tested with this command and confirmed the original bug (https://github.com/ossf/scorecard/pull/2557) is fixed.
```
docker run -e INPUT_REPO_TOKEN="$GITHUB_AUTH_TOKEN" \
-e INPUT_POLICY_FILE="/policy.yml" \
-e INPUT_RESULTS_FORMAT="sarif" \
-e INPUT_RESULTS_FILE="results.sarif" \
-e INPUT_PUBLISH_RESULTS="false" \
-e GITHUB_WORKSPACE="/github/workflow" \
-e GITHUB_REF="refs/heads/main" \
-e GITHUB_EVENT_NAME="branch_protection_rule" \
-e …
```

🌱 Bump docker tag for new release.

---

signing/signing.go

Fixes #1141 #1142 
Cosign added a privacy confirmation prompt before uploading to the tlog, which causes scorecard action to fail as we dont run interactively. 
This PR adds the equivalent of the following cosign CLI option:
```
-y, --yes   skip confirmation prompts for non-destructive operations
```
Related: https://github.com/ossf/scorecard/pull/2918

:bug: Skip cosign confirmation prompt when publishing scorecard results.

---

.github/workflows/golangci.yml
.golangci.yml

We don't use depguard and it's failing (https://github.com/ossf/scorecard-webapp/pull/407). structcheck is deprecated.
Removed `fix: true` because the linter workflow doesnt have permissions to change contents anyway.
Reduced read permissions on the action as we only need `contents: read`

:seedling: Disable depguard and structcheck linters.

---

README.md

First step towards addressing #1150
I also updated some versions in the example workflow.

:book: Document the GitHub action workflow restrictions when publishing results.

---

README.md

Links to the new visualizer introduced in https://github.com/ossf/scorecard/issues/2979.

:book: Switch recommended badge link to the new viewer.

---

signing/signing.go
signing/signing_test.go

Recreation of #1037 with a variable backoff. This backoff is used for both interactions with Sigstore, and interactions with our own webapp.
These issues are cropping up more frequently:
Fixes #1190
Fixes #1189
Fixes #1188
Fixes #1186
Fixes #1179
Fixes #1177
Fixes #1163
Fixes #1157
Fixes #1148
Fixes #1132

:seedling: Retry external network calls when publishing results

---

action.yaml

Notable changes (will be more detailed in release notes)
* Scorecard bump to v4.11.0
* Scorecard Result Viewer, highlighting the badge linking instructions
* Publishing result QoL changes
* Runs that fail our workflow restrictions will fail with a 400 response indicating the problem, instead of a vague 500 status. 
* Scorecard action will retry when signing results and submitting them to our web API. This should help with flakiness from connection failures
* doc changes
* fine-grained tokens instructions
* updated action installation instructions

:seedling: Bump docker tag for v2.2.0 release.

---

README.md

GitHub has changed the visibility of the alerts to every contributor with `write` access instead of only admins. `maintainers` as previously mentioned in the text is a different security role. More info [in the docs here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/managing-code-scanning-alerts-for-your-repository).
This PR updates the wording so it is correct again.

Update access rights needed to see the results in code scanning

---

entrypoint/entrypoint.go
github/github.go
install/cli/cli.go
install/github/github.go
install/install.go
install/options/options.go
main.go

The linter (when run on commits to main after merge) has been failing due to these for a while now. I took my best guess on a short description for these.

:book: Add package comments.

---

github/github.go

We want to run this action against our internal GHES instance which is now supported with the release of [scorecard v4.11.0](https://github.com/ossf/scorecard/releases/tag/v4.11.0). 
The call I changed makes the path to the API call additive, where as baseURL.Parse removed the last part of the url. For example, with the Parse method `https://github.corp.com/api/v3` became `https://github.corp.com/api/repos/<reponame>` which ofc does not resolve.
With this change the URL is correct.  
> Note: 
This is the first step in getting support for running this against your own GHES instance. The next is authenticating the calls to the repos end point, but I want to create a separate PR for that (I have a crude version working against our internal server). That should also remediate a lot of [this …

Prevent url clipping for GHES instances

---

README.md
SECURITY.md

This commit adds a SECURITY.md file, so panicked reporters will know how to report them. Since private reporting is enabled, I presume that's how this group wants the vulnerabilities reported.
I also tweaked the README to point to it.

Add SECURITY.md file

---

README.md

It's trivial but annoying because the workflow doesn't fail when using `repo-token` but shows a warning in the annotation section.
```
Unexpected input(s) 'repo-token', valid inputs are ['entryPoint', 'args', 'results_file', 'results_format', 'repo_token', 'publish_results', 'internal_publish_base_url', 'internal_default_token']
```

Fix typo in token input docs

---

Dockerfile
go.mod

One of our dependencies specifies 1.20 in its `go.mod`, so the upgrade is failing. (#1254). At some point we'll probably need to bump again to 1.21. 
Note: our Dockerfile already uses 1.21, but ultimately the runtime behavior is based on whats in our go.mod

:seedling: Upgrade to go 1.20

---

action.yaml

Notable changes (will be more detailed in release notes)
* Scorecard bump to v4.13.0
* Which includes some scoring changes and repo rules support
* Small change in what we send to the webapp when publishing results
* documentation changes
I ran the nightly e2e tests after upgrading to scorecard v4.13.0 and they all passed:
https://github.com/ossf-tests/scorecard-action/actions/runs/6434998535

:seedling: Bump docker tag to for v2.3.0 release.

---

.github/dependabot.yml

The majority of our dependency updates are GitHub Action updates, and Dockerfile updates. The Go updates have a more direct effect on the code and are more spread out, so I didn't group them.
https://github.com/ossf/scorecard-action/pulls?q=is%3Apr+label%3Adependencies+is%3Aclosed

:seedling: Group Dependabot updates for GitHub Actions and Dockerfiles

---

README.md

This way dependabot will keep the workflow updated for us, and we don't need to remember to update anything here.
Fixes https://github.com/ossf/scorecard/issues/3968

:book: link to `ossf/scorecard` workflow instead of maintaining an example

---

.github/workflows/golangci.yml
.golangci.yml

If we don't set it, the action uses the latest release, which changes outside our control.
Version changes should be controlled, as new linter versions often lead to new findings which need to be dealt with.
Also use `timeout` instead of `deadline` in our configuration.
`deadline` was deprecated in 2019 and support was removed in v1.57.0 of golangci-lint

:seedling: specify `golangci-lint` version in action

---

README.md
action.yaml

As mentioned in our blog post, and in slack, we're favoring scorecard.dev instead of securityscorecards.dev https://openssf.org/blog/2024/03/05/openssf-scorecard-evaluating-and-improving-the-health-of-critical-oss-projects/

:book: update api links to new scorecard.dev site

---

Makefile
go.mod
go.sum

Includes the ossf/scorecard#4097 bug fix before cutting v2.3.2

:seedling: Bump github.com/ossf/scorecard/v5 from v5.0.0-rc2 to v5.0.0-rc2.0.20240509182734-7ce860946928

---

action.yaml

The main change is the Scorecard bump to v5.0.0, which includes maintainer annotations which will affect the SARIF produced by this action.
For full details see the release notes:
https://github.com/ossf/scorecard/releases/tag/v5.0.0

bump docker tag to v2.4.0 for release

---

internal/scorecard/format.go
main.go

There were two issues at play that prevented the binary from reading the correct results file:
1. The paths were not joined with a separator during the refactor in #1423. This led to file not found errors, as the file was saved in the wrong directory, with the wrong name.
2. The signing code tried to read the file from the working directory instead of the GitHub workspace directory.
I was able to test this code after modifying the testing command in the `Dockerfile` to use a different `GITHUB_WORKSPACE` directory. The signing portion of the code will need to wait until the e2e test to confirm the fix.
We should eventually improve the [testing instructions](https://github.com/ossf/scorecard-action/blob/ab9729375aeb5f298cbbdcf9167c9fd974416537/Dockerfile#L15-L23), but at least the e2e test …

fix result file path issues

---

options/options.go

Currently one has to open the action log and scroll down to the bottom to understand the problem...

Make default branch error more prominent

---

Makefile
README.md
action.yaml
go.mod
go.sum
internal/scorecard/scorecard.go
options/env.go
options/options.go
options/options_test.go

Introduced upstream in https://github.com/ossf/scorecard/pull/4474
Also updates Scorecard to v5.1.1 for the data race fix.

add input for specifying `--file-mode`

---

Makefile

The detected info is interfering with the manually specified Scorecard version in the LDFLAGS. While `buildvcs` has been present since Go 1.18, Go 1.24 changed the behavior again. Our docker image uses Go 1.24 as of 3676bbc29082184ac34a84d1573c0419f81c4a68.
https://go.dev/doc/go1.24#go-command
> The go build command now sets the [main module’s version](https://go.dev/pkg/runtime/debug#BuildInfo.Main) in the compiled binary based on the version control system tag and/or commit. A +dirty suffix will be appended if there are uncommitted changes. Use the -buildvcs=false flag to omit version control information from the binary.
This trickled down to the produced output:
Before this PR:
```json
"scorecard": { 
"version":"v0.0.0-20250218152336-6a62a1cbf280", …
```

omit vcs info from build

---

RELEASE.md
action.yaml

This includes both the version bump, and uses the new GHCR image.
Initially sent as a draft PR, as there are a few steps left in the process:
Fixes #1473 
Fixes #1499

:seedling: bump docker to ghcr v2.4.1

---

Makefile
go.mod
go.sum

https://github.com/ossf/scorecard/releases/tag/v5.2.1

:seedling: Bump github.com/ossf/scorecard/v5 from v5.2.0 to v5.2.1

---

.github/workflows/codeql-analysis.yml
.github/workflows/docker-image.yml

Improve the `Token Permissions` score, see https://scorecard.dev/viewer/?uri=github.com/ossf/scorecard-action
```
Reason
detected GitHub workflow tokens with excessive permissions
Details
Info: jobLevel 'actions' permission set to 'read': .github/workflows/codeql-analysis.yml:28
Info: jobLevel 'contents' permission set to 'read': .github/workflows/codeql-analysis.yml:29
Warn: jobLevel 'packages' permission set to 'write': .github/workflows/ghcr-retention.yml:13
Warn: no topLevel permission defined: .github/workflows/codeql-analysis.yml:1
Info: topLevel 'contents' permission set to 'read': .github/workflows/dependency-review.yml:27
Warn: no topLevel permission defined: .github/workflows/docker-image.yml:1
Info: found token with 'none' permissions: .github/workflows/ghcr-retention.yml:1 …
```

add missing top-level token permissions to workflows

---

.github/CODEOWNERS

https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/

setup codeowners for requesting reviews

---

README.md

What
- Add a short subsection showing the additional job-level read permissions often needed when running Scorecard Action on private repositories (issues, pull-requests, checks), alongside the existing guidance for id-token/security-events.
- Include a minimal YAML example and brief rationale.
Why
- Without these, private repos can hit `Resource not accessible by integration` during GraphQL ListCommits and miss SAST detection. See #1248.
Notes
- Keeps least-privilege: adds only read scopes needed for the job; write scopes are limited to security-events (SARIF) and id-token (if publishing).
Fixes #1248

docs: clarify `GITHUB_TOKEN` permissions needed for private repos

---

docs/development.md

Because no testdata files are actually copied to the image, we fail to read the event file and fallback to fetching the information from GitHub API.
Howver, that's not actually working because the `GITHUB_API_URL` environment is missing.
To fix it, we could pass the `GITHUB_API_URL`. However, I think actually making the testdata file available to the container mimics better what happens in real life.
This is an alternative to #1582.

:book: Fix recommended command to test the image in development
